WIP - Create helm chart and OCM package for watcher
kyma-project/kyma-watcher pull request #9
Opened 2022-07-12 15:49 UTC by khlifi411

2022-07-26 08:29 UTC, jeremyharisch reviewed
Please create a smaller section in the README describing how to use the scripts and create the OCM image.

2022-07-26 08:29 UTC, jeremyharisch commented on skr/Makefile
> +helm-prepare: manifests kustomize ## Deploy controller to the K8s cluster specified in ~/.kube/config.
This just creates the yaml for the helm chart, right? And does not deploy anything as mentioned in the comment. Please adapt comment

2022-07-28 06:37 UTC, adityabhatia commented on ocm/samples/sample-manifest.yaml
> +  #     randomkey: samplevalue
please remove commented lines

2022-07-28 06:37 UTC, adityabhatia commented on ocm/scripts/prepare-watcher-chart.sh
> +MAKEFILE_PATH="${REPO_ROOT}/operator"
this path is not correct

2022-07-28 06:38 UTC, adityabhatia commented on ocm/scripts/prepare-watcher-chart.sh
> +WATCHER_CHART_PATH="${HELM_CHARTS_PATH}/kyma-watcher"
please rename to skr-watcher

2022-07-28 06:39 UTC, adityabhatia commented on ocm/scripts/prepare-watcher-chart.sh
> +mkdir -p "${HELM_CHART_TEMPLATES_DIR}" && make -C "${MAKEFILE_PATH}" helm-prepare
why is templates folder already not a part of charts

2022-07-28 06:47 UTC, adityabhatia commented on ocm/scripts/watcher-ocm-create.sh
> +MODULE_NAME="kyma-project.io/module/kyma-watcher/operator"
this needs correction
```suggestion
MODULE_NAME="kyma-project.io/module/kyma-watcher/skr"
```

2022-07-28 06:48 UTC, adityabhatia commented on ocm/scripts/watcher-ocm-push.sh
> +"$COMPONENT_CLI" archive remote push ${OCM_PACKAGE_PATH} --repo-ctx ${K3D_REGISTRY_SOCKET}
create and push scripts can be combined for simplicity

2022-07-28 06:58 UTC, adityabhatia commented on ocm/scripts/gen-manifest-cr.sh
> +EOF
this can be combines with the archive create and push. Otherwise it's confusing to find what's happening where.

2022-07-28 07:00 UTC, adityabhatia commented on skr/config/manager/kustomization.yaml
> +  newName: k3d-registry.localhost:4000/kyma-watcher
please add a placeholder here, it will fail and the user will know what's missing
```suggestion
  newName: <your-own-skr-watcher-image>
```

2022-07-28 07:01 UTC, adityabhatia commented on ocm/samples/sample-manifest.yaml
> +      name: watcher-chart # same name as chart for which the config will be applied
this sample file should not be a part of this repo, but rather should be taken from the manifest-operator for consistency reasons

2022-07-28 07:02 UTC, adityabhatia commented on ocm/resources/watcher-ocm-resources.yaml
> +#   path: "./crds" # path is relative to the current resource file
remove commented lines

2022-07-28 07:03 UTC, adityabhatia commented on ocm/scripts/watcher-ocm-push.sh
> +K3D_REGISTRY_PORT="4000"
please create a placeholder for registry and port

2022-07-28 07:04 UTC, adityabhatia commented on skr/Makefile
> +IMG ?= k3d-registry.localhost:4000/kyma-watcher:latest
we do not know for sure if users will use a k3d registry, so please make as generic as possible

2022-07-28 07:05 UTC, adityabhatia commented on ocm/samples/watcher-manifest-cr.yaml
> +      name: watcher-chart
please remove as said above for consistency reasons

2022-07-28 07:06 UTC, adityabhatia commented on ocm/ocm-descriptors/component-descriptor.yaml
> +  schemaVersion: v2
please remove, this should be generated

2022-07-28 07:07 UTC, adityabhatia requested changes
the helm chart and generator files should not be placed in the root dir, since it only concerns skr watcher. It should go to kyma-watcher/skr/chart

2022-07-28 09:08 UTC, khlifi411 commented
As discussed in our call, I have removed the scripts and applied your suggestions. 👍

2022-07-28 13:11 UTC, khlifi411 commented
/retest-required

2022-07-28 13:11 UTC, khlifi411 commented
/retest

2022-07-29 06:19 UTC, khlifi411 commented
/test pre-main-kyma-watcher-skr-lint

2022-07-29 07:30 UTC, adityabhatia commented
Looks good 🔥  but the lint test it still failing. 
Also the helm chart path looks like `kyma-watcher/skr/skr-watcher-helm-chart`
Can we make it a bit simpler like `kyma-watcher/skr/chart`?

2022-07-29 08:01 UTC, khlifi411 commented
> Looks good 🔥 but the lint test it still failing. Also the helm chart path looks like `kyma-watcher/skr/skr-watcher-helm-chart` Can we make it a bit simpler like `kyma-watcher/skr/chart`?

Thanks for the feedback! I have simplified the chart path as you suggested 😄 
 Lint test looks green now as issues were fixed by #34 👍

2022-07-29 08:04 UTC, adityabhatia approved these changes

2022-07-29 08:04 UTC, merged

2022-07-29 08:06 UTC, khlifi411 commented on skr/skr-watcher-helm-chart/templates/.gitignore
> +# Ignore everything in this directory
Yes. In order to ignore generated `.yaml` files and include the `templates` directory so that we don't need to create it.

2022-07-29 08:07 UTC, khlifi411 commented on skr/config/manager/kustomization.yaml
> +  newName: k3d-registry.localhost:4000/kyma-watcher
This is generated. When you have your right image, it will be overridden.